In [1]:
import matplotlib.pyplot as plt
import numpy as np
from typing import Callable, List, Dict, Any, Set, FrozenSet, Iterable, Tuple
import math
import random
import networkx as nx
import sympy as sym

import os
import galois

from HC_ZN_functions import *

In [2]:
from joblib import Parallel, delayed

import time 

In [3]:
def sim_code(code,p):
    commutator = lambda a,b: (a[0] @ b[0] - a[1]@b[1]) % code.q
    
    counter = 0
    code.make_error(p)
    code.final_pauli(my_HC_decoder(code,code.E)[0])

    if commutator(code.error_XZ, code.L1vf) != 0: # or commutator(code.L1h, code.error_XZ) !=0: 
        counter +=1

    return counter

In [4]:
code1 = HC_code(2,2,2)
code1.make_tanner_graph()
code1.make_H()
code1.logicals()
code1.parity_check_physical()

code1.h_sites_f

[((1+2j), 'X'),
 ((3+2j), 'Y'),
 ((1+1j), 'X dag'),
 ((3+1j), 'Y dag'),
 ((5+2j), 'X'),
 ((7+2j), 'Y'),
 ((5+1j), 'X dag'),
 ((7+1j), 'Y dag')]

In [5]:
sim_code(code1, .01)

0

In [6]:
commutator = lambda a,b: (a[0] @ b[0] - a[1]@b[1]) % code1.q

In [7]:
commutator(code1.HC_parity_check, code1.L1hf)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [8]:
code1.L1hf

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [9]:
code1.HC_parity_check

array([[[0., 1., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 1., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [10]:
distance = 3

h_sites_f=[] #(sites, paulis) in horizontal logical, lives on blue edges
h_sites_e =[]
for n in range(1, 4*distance, 4):
    #h_sites_f.append( ((n-2)% (4*distance) + 1j*(6*distance-1), 'Y'))
    #h_sites_f.append( ((n)% (4*distance) + 1j*(6*distance-1), 'Y dag'))
    #h_sites_f.append( ((n-2)% (4*distance), 'Y dag'))
    #h_sites_f.append( ((n)% (4*distance), 'Y'))

    h_sites_f.append( ((n)% (4*distance) + 2j, 'X'))
    h_sites_f.append( ((n+2)% (4*distance) + 2j, 'X dag'))

    h_sites_f.append( ((n)% (4*distance) +1j, 'X dag'))
    h_sites_f.append( ((n+2)% (4*distance) +1j, 'X'))

    #old logical 
    h_sites_e.append( ((n-2)% (4*distance) + 2j, 'Y'))
    h_sites_e.append( ((n)% (4*distance) + 2j, 'Y dag'))

In [11]:
h_sites_f

[((1+2j), 'X'),
 ((3+2j), 'X dag'),
 ((1+1j), 'X dag'),
 ((3+1j), 'X'),
 ((5+2j), 'X'),
 ((7+2j), 'X dag'),
 ((5+1j), 'X dag'),
 ((7+1j), 'X'),
 ((9+2j), 'X'),
 ((11+2j), 'X dag'),
 ((9+1j), 'X dag'),
 ((11+1j), 'X')]